package com.example.demo.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class ActionResult implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.result_id
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private Integer resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.task_id
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.top1
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private String top1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.top2
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private String top2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.top3
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private String top3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.top4
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private String top4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.top5
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private String top5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.is_danger
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private Integer isDanger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.result_date
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private Date resultDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.is_right
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private Integer isRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_result.state
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.result_id
     *
     * @return the value of action_result.result_id
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public Integer getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.result_id
     *
     * @param resultId the value for action_result.result_id
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setResultId(Integer resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.task_id
     *
     * @return the value of action_result.task_id
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.task_id
     *
     * @param taskId the value for action_result.task_id
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.top1
     *
     * @return the value of action_result.top1
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public String getTop1() {
        return top1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.top1
     *
     * @param top1 the value for action_result.top1
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setTop1(String top1) {
        this.top1 = top1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.top2
     *
     * @return the value of action_result.top2
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public String getTop2() {
        return top2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.top2
     *
     * @param top2 the value for action_result.top2
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setTop2(String top2) {
        this.top2 = top2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.top3
     *
     * @return the value of action_result.top3
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public String getTop3() {
        return top3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.top3
     *
     * @param top3 the value for action_result.top3
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setTop3(String top3) {
        this.top3 = top3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.top4
     *
     * @return the value of action_result.top4
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public String getTop4() {
        return top4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.top4
     *
     * @param top4 the value for action_result.top4
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setTop4(String top4) {
        this.top4 = top4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.top5
     *
     * @return the value of action_result.top5
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public String getTop5() {
        return top5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.top5
     *
     * @param top5 the value for action_result.top5
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setTop5(String top5) {
        this.top5 = top5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.is_danger
     *
     * @return the value of action_result.is_danger
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public Integer getIsDanger() {
        return isDanger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.is_danger
     *
     * @param isDanger the value for action_result.is_danger
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setIsDanger(Integer isDanger) {
        this.isDanger = isDanger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.result_date
     *
     * @return the value of action_result.result_date
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public Date getResultDate() {
        return resultDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.result_date
     *
     * @param resultDate the value for action_result.result_date
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setResultDate(Date resultDate) {
        this.resultDate = resultDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.is_right
     *
     * @return the value of action_result.is_right
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public Integer getIsRight() {
        return isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.is_right
     *
     * @param isRight the value for action_result.is_right
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setIsRight(Integer isRight) {
        this.isRight = isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_result.state
     *
     * @return the value of action_result.state
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_result.state
     *
     * @param state the value for action_result.state
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }
}