package com.example.demo.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActionResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public ActionResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResultIdIsNull() {
            addCriterion("result_id is null");
            return (Criteria) this;
        }

        public Criteria andResultIdIsNotNull() {
            addCriterion("result_id is not null");
            return (Criteria) this;
        }

        public Criteria andResultIdEqualTo(Integer value) {
            addCriterion("result_id =", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdNotEqualTo(Integer value) {
            addCriterion("result_id <>", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdGreaterThan(Integer value) {
            addCriterion("result_id >", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("result_id >=", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdLessThan(Integer value) {
            addCriterion("result_id <", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdLessThanOrEqualTo(Integer value) {
            addCriterion("result_id <=", value, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdIn(List<Integer> values) {
            addCriterion("result_id in", values, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdNotIn(List<Integer> values) {
            addCriterion("result_id not in", values, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdBetween(Integer value1, Integer value2) {
            addCriterion("result_id between", value1, value2, "resultId");
            return (Criteria) this;
        }

        public Criteria andResultIdNotBetween(Integer value1, Integer value2) {
            addCriterion("result_id not between", value1, value2, "resultId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Integer value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Integer value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Integer value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Integer value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Integer> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Integer> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Integer value1, Integer value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTop1IsNull() {
            addCriterion("top1 is null");
            return (Criteria) this;
        }

        public Criteria andTop1IsNotNull() {
            addCriterion("top1 is not null");
            return (Criteria) this;
        }

        public Criteria andTop1EqualTo(String value) {
            addCriterion("top1 =", value, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1NotEqualTo(String value) {
            addCriterion("top1 <>", value, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1GreaterThan(String value) {
            addCriterion("top1 >", value, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1GreaterThanOrEqualTo(String value) {
            addCriterion("top1 >=", value, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1LessThan(String value) {
            addCriterion("top1 <", value, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1LessThanOrEqualTo(String value) {
            addCriterion("top1 <=", value, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1Like(String value) {
            addCriterion("top1 like", value, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1NotLike(String value) {
            addCriterion("top1 not like", value, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1In(List<String> values) {
            addCriterion("top1 in", values, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1NotIn(List<String> values) {
            addCriterion("top1 not in", values, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1Between(String value1, String value2) {
            addCriterion("top1 between", value1, value2, "top1");
            return (Criteria) this;
        }

        public Criteria andTop1NotBetween(String value1, String value2) {
            addCriterion("top1 not between", value1, value2, "top1");
            return (Criteria) this;
        }

        public Criteria andTop2IsNull() {
            addCriterion("top2 is null");
            return (Criteria) this;
        }

        public Criteria andTop2IsNotNull() {
            addCriterion("top2 is not null");
            return (Criteria) this;
        }

        public Criteria andTop2EqualTo(String value) {
            addCriterion("top2 =", value, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2NotEqualTo(String value) {
            addCriterion("top2 <>", value, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2GreaterThan(String value) {
            addCriterion("top2 >", value, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2GreaterThanOrEqualTo(String value) {
            addCriterion("top2 >=", value, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2LessThan(String value) {
            addCriterion("top2 <", value, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2LessThanOrEqualTo(String value) {
            addCriterion("top2 <=", value, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2Like(String value) {
            addCriterion("top2 like", value, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2NotLike(String value) {
            addCriterion("top2 not like", value, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2In(List<String> values) {
            addCriterion("top2 in", values, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2NotIn(List<String> values) {
            addCriterion("top2 not in", values, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2Between(String value1, String value2) {
            addCriterion("top2 between", value1, value2, "top2");
            return (Criteria) this;
        }

        public Criteria andTop2NotBetween(String value1, String value2) {
            addCriterion("top2 not between", value1, value2, "top2");
            return (Criteria) this;
        }

        public Criteria andTop3IsNull() {
            addCriterion("top3 is null");
            return (Criteria) this;
        }

        public Criteria andTop3IsNotNull() {
            addCriterion("top3 is not null");
            return (Criteria) this;
        }

        public Criteria andTop3EqualTo(String value) {
            addCriterion("top3 =", value, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3NotEqualTo(String value) {
            addCriterion("top3 <>", value, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3GreaterThan(String value) {
            addCriterion("top3 >", value, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3GreaterThanOrEqualTo(String value) {
            addCriterion("top3 >=", value, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3LessThan(String value) {
            addCriterion("top3 <", value, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3LessThanOrEqualTo(String value) {
            addCriterion("top3 <=", value, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3Like(String value) {
            addCriterion("top3 like", value, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3NotLike(String value) {
            addCriterion("top3 not like", value, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3In(List<String> values) {
            addCriterion("top3 in", values, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3NotIn(List<String> values) {
            addCriterion("top3 not in", values, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3Between(String value1, String value2) {
            addCriterion("top3 between", value1, value2, "top3");
            return (Criteria) this;
        }

        public Criteria andTop3NotBetween(String value1, String value2) {
            addCriterion("top3 not between", value1, value2, "top3");
            return (Criteria) this;
        }

        public Criteria andTop4IsNull() {
            addCriterion("top4 is null");
            return (Criteria) this;
        }

        public Criteria andTop4IsNotNull() {
            addCriterion("top4 is not null");
            return (Criteria) this;
        }

        public Criteria andTop4EqualTo(String value) {
            addCriterion("top4 =", value, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4NotEqualTo(String value) {
            addCriterion("top4 <>", value, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4GreaterThan(String value) {
            addCriterion("top4 >", value, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4GreaterThanOrEqualTo(String value) {
            addCriterion("top4 >=", value, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4LessThan(String value) {
            addCriterion("top4 <", value, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4LessThanOrEqualTo(String value) {
            addCriterion("top4 <=", value, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4Like(String value) {
            addCriterion("top4 like", value, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4NotLike(String value) {
            addCriterion("top4 not like", value, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4In(List<String> values) {
            addCriterion("top4 in", values, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4NotIn(List<String> values) {
            addCriterion("top4 not in", values, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4Between(String value1, String value2) {
            addCriterion("top4 between", value1, value2, "top4");
            return (Criteria) this;
        }

        public Criteria andTop4NotBetween(String value1, String value2) {
            addCriterion("top4 not between", value1, value2, "top4");
            return (Criteria) this;
        }

        public Criteria andTop5IsNull() {
            addCriterion("top5 is null");
            return (Criteria) this;
        }

        public Criteria andTop5IsNotNull() {
            addCriterion("top5 is not null");
            return (Criteria) this;
        }

        public Criteria andTop5EqualTo(String value) {
            addCriterion("top5 =", value, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5NotEqualTo(String value) {
            addCriterion("top5 <>", value, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5GreaterThan(String value) {
            addCriterion("top5 >", value, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5GreaterThanOrEqualTo(String value) {
            addCriterion("top5 >=", value, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5LessThan(String value) {
            addCriterion("top5 <", value, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5LessThanOrEqualTo(String value) {
            addCriterion("top5 <=", value, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5Like(String value) {
            addCriterion("top5 like", value, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5NotLike(String value) {
            addCriterion("top5 not like", value, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5In(List<String> values) {
            addCriterion("top5 in", values, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5NotIn(List<String> values) {
            addCriterion("top5 not in", values, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5Between(String value1, String value2) {
            addCriterion("top5 between", value1, value2, "top5");
            return (Criteria) this;
        }

        public Criteria andTop5NotBetween(String value1, String value2) {
            addCriterion("top5 not between", value1, value2, "top5");
            return (Criteria) this;
        }

        public Criteria andIsDangerIsNull() {
            addCriterion("is_danger is null");
            return (Criteria) this;
        }

        public Criteria andIsDangerIsNotNull() {
            addCriterion("is_danger is not null");
            return (Criteria) this;
        }

        public Criteria andIsDangerEqualTo(Integer value) {
            addCriterion("is_danger =", value, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerNotEqualTo(Integer value) {
            addCriterion("is_danger <>", value, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerGreaterThan(Integer value) {
            addCriterion("is_danger >", value, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_danger >=", value, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerLessThan(Integer value) {
            addCriterion("is_danger <", value, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerLessThanOrEqualTo(Integer value) {
            addCriterion("is_danger <=", value, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerIn(List<Integer> values) {
            addCriterion("is_danger in", values, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerNotIn(List<Integer> values) {
            addCriterion("is_danger not in", values, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerBetween(Integer value1, Integer value2) {
            addCriterion("is_danger between", value1, value2, "isDanger");
            return (Criteria) this;
        }

        public Criteria andIsDangerNotBetween(Integer value1, Integer value2) {
            addCriterion("is_danger not between", value1, value2, "isDanger");
            return (Criteria) this;
        }

        public Criteria andResultDateIsNull() {
            addCriterion("result_date is null");
            return (Criteria) this;
        }

        public Criteria andResultDateIsNotNull() {
            addCriterion("result_date is not null");
            return (Criteria) this;
        }

        public Criteria andResultDateEqualTo(Date value) {
            addCriterion("result_date =", value, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateNotEqualTo(Date value) {
            addCriterion("result_date <>", value, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateGreaterThan(Date value) {
            addCriterion("result_date >", value, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateGreaterThanOrEqualTo(Date value) {
            addCriterion("result_date >=", value, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateLessThan(Date value) {
            addCriterion("result_date <", value, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateLessThanOrEqualTo(Date value) {
            addCriterion("result_date <=", value, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateIn(List<Date> values) {
            addCriterion("result_date in", values, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateNotIn(List<Date> values) {
            addCriterion("result_date not in", values, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateBetween(Date value1, Date value2) {
            addCriterion("result_date between", value1, value2, "resultDate");
            return (Criteria) this;
        }

        public Criteria andResultDateNotBetween(Date value1, Date value2) {
            addCriterion("result_date not between", value1, value2, "resultDate");
            return (Criteria) this;
        }

        public Criteria andIsRightIsNull() {
            addCriterion("is_right is null");
            return (Criteria) this;
        }

        public Criteria andIsRightIsNotNull() {
            addCriterion("is_right is not null");
            return (Criteria) this;
        }

        public Criteria andIsRightEqualTo(Integer value) {
            addCriterion("is_right =", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightNotEqualTo(Integer value) {
            addCriterion("is_right <>", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightGreaterThan(Integer value) {
            addCriterion("is_right >", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_right >=", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightLessThan(Integer value) {
            addCriterion("is_right <", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightLessThanOrEqualTo(Integer value) {
            addCriterion("is_right <=", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightIn(List<Integer> values) {
            addCriterion("is_right in", values, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightNotIn(List<Integer> values) {
            addCriterion("is_right not in", values, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightBetween(Integer value1, Integer value2) {
            addCriterion("is_right between", value1, value2, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightNotBetween(Integer value1, Integer value2) {
            addCriterion("is_right not between", value1, value2, "isRight");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table action_result
     *
     * @mbg.generated do_not_delete_during_merge Mon Apr 11 21:41:01 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table action_result
     *
     * @mbg.generated Mon Apr 11 21:41:01 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}