package com.example.demo.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class AdminRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_record.record_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_record.user_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_record.evaluate_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer evaluateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_record.operation
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_record.create_date
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_record.state
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_record
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_record.record_id
     *
     * @return the value of admin_record.record_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_record.record_id
     *
     * @param recordId the value for admin_record.record_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_record.user_id
     *
     * @return the value of admin_record.user_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_record.user_id
     *
     * @param userId the value for admin_record.user_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_record.evaluate_id
     *
     * @return the value of admin_record.evaluate_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getEvaluateId() {
        return evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_record.evaluate_id
     *
     * @param evaluateId the value for admin_record.evaluate_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setEvaluateId(Integer evaluateId) {
        this.evaluateId = evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_record.operation
     *
     * @return the value of admin_record.operation
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_record.operation
     *
     * @param operation the value for admin_record.operation
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setOperation(Integer operation) {
        this.operation = operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_record.create_date
     *
     * @return the value of admin_record.create_date
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_record.create_date
     *
     * @param createDate the value for admin_record.create_date
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_record.state
     *
     * @return the value of admin_record.state
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_record.state
     *
     * @param state the value for admin_record.state
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }
}