package com.example.demo.dao.entity;

import java.io.Serializable;

public class DangerPerson implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_person.danger_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer dangerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_person.result_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_person.user_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_person.task_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_person.img_path
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_person.person_name
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private String personName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_person.is_right
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer isRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_person.state
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_person.danger_id
     *
     * @return the value of danger_person.danger_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getDangerId() {
        return dangerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_person.danger_id
     *
     * @param dangerId the value for danger_person.danger_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setDangerId(Integer dangerId) {
        this.dangerId = dangerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_person.result_id
     *
     * @return the value of danger_person.result_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_person.result_id
     *
     * @param resultId the value for danger_person.result_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setResultId(Integer resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_person.user_id
     *
     * @return the value of danger_person.user_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_person.user_id
     *
     * @param userId the value for danger_person.user_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_person.task_id
     *
     * @return the value of danger_person.task_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_person.task_id
     *
     * @param taskId the value for danger_person.task_id
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_person.img_path
     *
     * @return the value of danger_person.img_path
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_person.img_path
     *
     * @param imgPath the value for danger_person.img_path
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_person.person_name
     *
     * @return the value of danger_person.person_name
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_person.person_name
     *
     * @param personName the value for danger_person.person_name
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_person.is_right
     *
     * @return the value of danger_person.is_right
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getIsRight() {
        return isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_person.is_right
     *
     * @param isRight the value for danger_person.is_right
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setIsRight(Integer isRight) {
        this.isRight = isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_person.state
     *
     * @return the value of danger_person.state
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_person.state
     *
     * @param state the value for danger_person.state
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }
}