package com.example.demo.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class ResultEvaluate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.evaluate_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private Integer evaluateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.result_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private Integer resultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.user_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.task_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.is_true
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private Integer isTrue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.true_action
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private String trueAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.create_date
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.state
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_evaluate.task_name
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table result_evaluate
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.evaluate_id
     *
     * @return the value of result_evaluate.evaluate_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public Integer getEvaluateId() {
        return evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.evaluate_id
     *
     * @param evaluateId the value for result_evaluate.evaluate_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setEvaluateId(Integer evaluateId) {
        this.evaluateId = evaluateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.result_id
     *
     * @return the value of result_evaluate.result_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public Integer getResultId() {
        return resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.result_id
     *
     * @param resultId the value for result_evaluate.result_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setResultId(Integer resultId) {
        this.resultId = resultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.user_id
     *
     * @return the value of result_evaluate.user_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.user_id
     *
     * @param userId the value for result_evaluate.user_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.task_id
     *
     * @return the value of result_evaluate.task_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.task_id
     *
     * @param taskId the value for result_evaluate.task_id
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.is_true
     *
     * @return the value of result_evaluate.is_true
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public Integer getIsTrue() {
        return isTrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.is_true
     *
     * @param isTrue the value for result_evaluate.is_true
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setIsTrue(Integer isTrue) {
        this.isTrue = isTrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.true_action
     *
     * @return the value of result_evaluate.true_action
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public String getTrueAction() {
        return trueAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.true_action
     *
     * @param trueAction the value for result_evaluate.true_action
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setTrueAction(String trueAction) {
        this.trueAction = trueAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.create_date
     *
     * @return the value of result_evaluate.create_date
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.create_date
     *
     * @param createDate the value for result_evaluate.create_date
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.state
     *
     * @return the value of result_evaluate.state
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.state
     *
     * @param state the value for result_evaluate.state
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_evaluate.task_name
     *
     * @return the value of result_evaluate.task_name
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_evaluate.task_name
     *
     * @param taskName the value for result_evaluate.task_name
     *
     * @mbg.generated Sun Apr 17 13:43:05 CST 2022
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }
}