package com.example.demo.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class VideoTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.task_id
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.task_name
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.user_id
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.need_video
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer needVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.need_det
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer needDet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.priority
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.task_state
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer taskState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.file_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.result_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private String resultPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.create_date
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.update_date
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.is_danger
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer isDanger;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.is_right
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer isRight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.state
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_task.img_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private String imgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.task_id
     *
     * @return the value of video_task.task_id
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.task_id
     *
     * @param taskId the value for video_task.task_id
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.task_name
     *
     * @return the value of video_task.task_name
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.task_name
     *
     * @param taskName the value for video_task.task_name
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.user_id
     *
     * @return the value of video_task.user_id
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.user_id
     *
     * @param userId the value for video_task.user_id
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.need_video
     *
     * @return the value of video_task.need_video
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getNeedVideo() {
        return needVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.need_video
     *
     * @param needVideo the value for video_task.need_video
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setNeedVideo(Integer needVideo) {
        this.needVideo = needVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.need_det
     *
     * @return the value of video_task.need_det
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getNeedDet() {
        return needDet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.need_det
     *
     * @param needDet the value for video_task.need_det
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setNeedDet(Integer needDet) {
        this.needDet = needDet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.priority
     *
     * @return the value of video_task.priority
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.priority
     *
     * @param priority the value for video_task.priority
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.task_state
     *
     * @return the value of video_task.task_state
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getTaskState() {
        return taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.task_state
     *
     * @param taskState the value for video_task.task_state
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setTaskState(Integer taskState) {
        this.taskState = taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.file_path
     *
     * @return the value of video_task.file_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.file_path
     *
     * @param filePath the value for video_task.file_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.result_path
     *
     * @return the value of video_task.result_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public String getResultPath() {
        return resultPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.result_path
     *
     * @param resultPath the value for video_task.result_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setResultPath(String resultPath) {
        this.resultPath = resultPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.create_date
     *
     * @return the value of video_task.create_date
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.create_date
     *
     * @param createDate the value for video_task.create_date
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.update_date
     *
     * @return the value of video_task.update_date
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.update_date
     *
     * @param updateDate the value for video_task.update_date
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.is_danger
     *
     * @return the value of video_task.is_danger
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getIsDanger() {
        return isDanger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.is_danger
     *
     * @param isDanger the value for video_task.is_danger
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setIsDanger(Integer isDanger) {
        this.isDanger = isDanger;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.is_right
     *
     * @return the value of video_task.is_right
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getIsRight() {
        return isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.is_right
     *
     * @param isRight the value for video_task.is_right
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setIsRight(Integer isRight) {
        this.isRight = isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.state
     *
     * @return the value of video_task.state
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.state
     *
     * @param state the value for video_task.state
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_task.img_path
     *
     * @return the value of video_task.img_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_task.img_path
     *
     * @param imgPath the value for video_task.img_path
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
}