package com.example.demo.dao.mapper;

import com.example.demo.dao.entity.DangerPerson;
import com.example.demo.dao.entity.DangerPersonExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DangerPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    long countByExample(DangerPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    int deleteByExample(DangerPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    int deleteByPrimaryKey(Integer dangerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    int insert(DangerPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    int insertSelective(DangerPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    List<DangerPerson> selectByExample(DangerPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    DangerPerson selectByPrimaryKey(Integer dangerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    int updateByExampleSelective(@Param("record") DangerPerson record, @Param("example") DangerPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    int updateByExample(@Param("record") DangerPerson record, @Param("example") DangerPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    int updateByPrimaryKeySelective(DangerPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_person
     *
     * @mbg.generated Sun Apr 03 13:41:10 CST 2022
     */
    int updateByPrimaryKey(DangerPerson record);
}