package com.example.demo.dao.mapper;

import com.example.demo.dao.entity.VideoTask;
import com.example.demo.dao.entity.VideoTaskExample;
import java.util.List;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface VideoTaskMapper {
	
	/**
	 * 添加任务
	 * @param videoTask
	 * @return
	 */
	@Insert("insert into video_task(task_name,user_id,need_video,need_det,priority,task_state,"
    		+ "file_path,result_path,create_date,update_date,is_danger,is_right,state) values(#{taskName},#{userId},#{needVideo},#{needDet},#{priority},#{taskState},"
    		+ " #{filePath},#{resultPath},#{createDate},#{updateDate},#{isDanger},#{isRight},#{state})")
    @SelectKey(statement ="select last_insert_id()",keyProperty="taskId",before=false,resultType=int.class)
	int insertTask(VideoTask videoTask);
	
	@Update("update video_task set is_right=#{isRight} where task_id=#{taskId}")
	int updateIsRight(int taskId,int isRight);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    long countByExample(VideoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    int deleteByExample(VideoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    int insert(VideoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    int insertSelective(VideoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    List<VideoTask> selectByExample(VideoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    VideoTask selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    int updateByExampleSelective(@Param("record") VideoTask record, @Param("example") VideoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    int updateByExample(@Param("record") VideoTask record, @Param("example") VideoTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    int updateByPrimaryKeySelective(VideoTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_task
     *
     * @mbg.generated Tue Apr 12 22:04:43 CST 2022
     */
    int updateByPrimaryKey(VideoTask record);
}